### ISSUE TITLE
handle static files

### ISSUE THREAD

**Issue by hajsf** [orhun/zig-http-benchmarks#10]
Can you at a route showing how to handle the static files!

**Comment by orhun** [comment]
I don't think this is the right place to ask this. Feel free to ask in the comments of [my blog post](https://blog.orhun.dev/zig-bits-04/) since some other people might help there.

**Comment by hajsf** [comment]
> Feel free to ask in the comments of [my blog post](https://blog.orhun.dev/zig-bits-04/) since some other people might help there.

Done, I posted my question there, thanks
