### ISSUE TITLE
Curl Performance

### ISSUE THREAD

**Issue by xwiz** [orhun/zig-http-benchmarks#11]
Just curious, what version of curl did you use?

And also how about including a version for gzip enabled curl

`curl -H "Accept-Encoding: gzip" -X GET curl http://127.0.0.1:8000/get?[1-1000]`

**Comment by orhun** [comment]
> Just curious, what version of curl did you use?

Installed from the Arch repos:

```
curl 8.2.1 (x86_64-pc-linux-gnu) libcurl/8.2.1 OpenSSL/3.1.2 zlib/1.3 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.56.0
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

> And also how about including a version for gzip enabled curl

That would be great! Are you interested in making a PR?
